# -*- coding: utf-8 -*-

"""
paypalserversdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DisputeCategory(object):

    """Implementation of the 'Dispute Category' enum.

    The condition that is covered for the transaction.

    Attributes:
        ITEM_NOT_RECEIVED: The payer paid for an item that they did not
            receive.
        UNAUTHORIZED_TRANSACTION: The payer did not authorize the payment.

    """
    ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED'

    UNAUTHORIZED_TRANSACTION = 'UNAUTHORIZED_TRANSACTION'

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
