# -*- coding: utf-8 -*-

"""
paypalserversdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LiabilityShiftIndicator(object):

    """Implementation of the 'Liability Shift Indicator' enum.

    Liability shift indicator. The outcome of the issuer's authentication.

    Attributes:
        NO: Liability is with the merchant.
        POSSIBLE: Liability may shift to the card issuer.
        UNKNOWN: The authentication system is not available.

    """
    NO = 'NO'

    POSSIBLE = 'POSSIBLE'

    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
