# -*- coding: utf-8 -*-

"""
paypalserversdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OsType(object):

    """Implementation of the 'OS Type' enum.

    Operating System type of the device that the buyer is using.

    Attributes:
        ANDROID: Google Android OS.
        IOS: Apple OS typically found in Apple mobile devices.
        OTHER: Any other OS type.

    """
    ANDROID = 'ANDROID'

    IOS = 'IOS'

    OTHER = 'OTHER'

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
