# -*- coding: utf-8 -*-

"""
paypalserversdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PlanRequestStatus(object):

    """Implementation of the 'Plan Request Status' enum.

    The initial state of the plan. Allowed input values are CREATED and ACTIVE.

    Attributes:
        CREATED: The plan was created. You cannot create subscriptions for a
            plan in this state.
        INACTIVE: The plan is inactive.
        ACTIVE: The plan is active. You can only create subscriptions for a
            plan in this state.

    """
    CREATED = 'CREATED'

    INACTIVE = 'INACTIVE'

    ACTIVE = 'ACTIVE'

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
