"""paypalserversdk.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from paypalserversdk.api_helper import APIHelper
from paypalserversdk.models.merchant_preferences import (
    MerchantPreferences,
)
from paypalserversdk.models.payment_preferences import (
    PaymentPreferences,
)
from paypalserversdk.models.subscription_billing_cycle import (
    SubscriptionBillingCycle,
)
from paypalserversdk.models.taxes import Taxes


class PlanDetails(object):
    """Implementation of the 'Plan Details' model.

    The plan details.

    Attributes:
        product_id (str): The ID for the product.
        name (str): The plan name.
        description (str): The detailed description of the plan.
        billing_cycles (List[SubscriptionBillingCycle]): An array of billing cycles
            for trial billing and regular billing. A plan can have at most two trial
            cycles and only one regular cycle.
        payment_preferences (PaymentPreferences): The payment preferences for a
            subscription.
        merchant_preferences (MerchantPreferences): The merchant preferences for a
            subscription.
        taxes (Taxes): The tax details.
        quantity_supported (bool): Indicates whether you can subscribe to this plan
            by providing a quantity for the goods or service.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "product_id": "product_id",
        "name": "name",
        "description": "description",
        "billing_cycles": "billing_cycles",
        "payment_preferences": "payment_preferences",
        "merchant_preferences": "merchant_preferences",
        "taxes": "taxes",
        "quantity_supported": "quantity_supported",
    }

    _optionals = [
        "product_id",
        "name",
        "description",
        "billing_cycles",
        "payment_preferences",
        "merchant_preferences",
        "taxes",
        "quantity_supported",
    ]

    def __init__(
        self,
        product_id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        description=APIHelper.SKIP,
        billing_cycles=APIHelper.SKIP,
        payment_preferences=APIHelper.SKIP,
        merchant_preferences=APIHelper.SKIP,
        taxes=APIHelper.SKIP,
        quantity_supported=False):
        """Initialize a PlanDetails instance."""
        # Initialize members of the class
        if product_id is not APIHelper.SKIP:
            self.product_id = product_id
        if name is not APIHelper.SKIP:
            self.name = name
        if description is not APIHelper.SKIP:
            self.description = description
        if billing_cycles is not APIHelper.SKIP:
            self.billing_cycles = billing_cycles
        if payment_preferences is not APIHelper.SKIP:
            self.payment_preferences = payment_preferences
        if merchant_preferences is not APIHelper.SKIP:
            self.merchant_preferences = merchant_preferences
        if taxes is not APIHelper.SKIP:
            self.taxes = taxes
        self.quantity_supported = quantity_supported

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        product_id =\
            dictionary.get("product_id")\
            if dictionary.get("product_id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        billing_cycles = None
        if dictionary.get("billing_cycles") is not None:
            billing_cycles = [
                SubscriptionBillingCycle.from_dictionary(x)
                    for x in dictionary.get("billing_cycles")
            ]
        else:
            billing_cycles = APIHelper.SKIP
        payment_preferences =\
            PaymentPreferences.from_dictionary(
                dictionary.get("payment_preferences"))\
                if "payment_preferences" in dictionary.keys()\
                else APIHelper.SKIP
        merchant_preferences =\
            MerchantPreferences.from_dictionary(
                dictionary.get("merchant_preferences"))\
                if "merchant_preferences" in dictionary.keys()\
                else APIHelper.SKIP
        taxes =\
            Taxes.from_dictionary(
                dictionary.get("taxes"))\
                if "taxes" in dictionary.keys()\
                else APIHelper.SKIP
        quantity_supported =\
            dictionary.get("quantity_supported")\
            if dictionary.get("quantity_supported")\
                else False

        # Return an object of this model
        return cls(product_id,
                   name,
                   description,
                   billing_cycles,
                   payment_preferences,
                   merchant_preferences,
                   taxes,
                   quantity_supported)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _product_id=(
            self.product_id
            if hasattr(self, "product_id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _billing_cycles=(
            self.billing_cycles
            if hasattr(self, "billing_cycles")
            else None
        )
        _payment_preferences=(
            self.payment_preferences
            if hasattr(self, "payment_preferences")
            else None
        )
        _merchant_preferences=(
            self.merchant_preferences
            if hasattr(self, "merchant_preferences")
            else None
        )
        _taxes=(
            self.taxes
            if hasattr(self, "taxes")
            else None
        )
        _quantity_supported=(
            self.quantity_supported
            if hasattr(self, "quantity_supported")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"product_id={_product_id!r}, "
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"billing_cycles={_billing_cycles!r}, "
            f"payment_preferences={_payment_preferences!r}, "
            f"merchant_preferences={_merchant_preferences!r}, "
            f"taxes={_taxes!r}, "
            f"quantity_supported={_quantity_supported!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _product_id=(
            self.product_id
            if hasattr(self, "product_id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _billing_cycles=(
            self.billing_cycles
            if hasattr(self, "billing_cycles")
            else None
        )
        _payment_preferences=(
            self.payment_preferences
            if hasattr(self, "payment_preferences")
            else None
        )
        _merchant_preferences=(
            self.merchant_preferences
            if hasattr(self, "merchant_preferences")
            else None
        )
        _taxes=(
            self.taxes
            if hasattr(self, "taxes")
            else None
        )
        _quantity_supported=(
            self.quantity_supported
            if hasattr(self, "quantity_supported")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"product_id={_product_id!s}, "
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"billing_cycles={_billing_cycles!s}, "
            f"payment_preferences={_payment_preferences!s}, "
            f"merchant_preferences={_merchant_preferences!s}, "
            f"taxes={_taxes!s}, "
            f"quantity_supported={_quantity_supported!s}, "
            f")"
        )
