# -*- coding: utf-8 -*-

"""
paypalserversdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SetupFeeFailureAction(object):

    """Implementation of the 'Setup Fee Failure Action' enum.

    The action to take on the subscription if the initial payment for the
    setup fails.

    Attributes:
        CONTINUE: Continues the subscription if the initial payment for the
            setup fails.
        CANCEL: Cancels the subscription if the initial payment for the setup
            fails.

    """
    CONTINUE = 'CONTINUE'

    CANCEL = 'CANCEL'

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
