# -*- coding: utf-8 -*-

"""
paypalserversdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from paypalserversdk.api_helper import APIHelper
from paypalserversdk.models.apple_pay_request_card import ApplePayRequestCard


class VaultApplePayRequest(object):

    """Implementation of the 'Vault Apple Pay Request' model.

    A resource representing a request to vault Apple Pay.

    Attributes:
        token (str): Encrypted Apple Pay token, containing card information.
            This token would be base64 encoded.
        card (ApplePayRequestCard): The payment card to be used to fund a
            payment. Can be a credit or debit card.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "token": 'token',
        "card": 'card'
    }

    _optionals = [
        'token',
        'card',
    ]

    def __init__(self,
                 token=APIHelper.SKIP,
                 card=APIHelper.SKIP):
        """Constructor for the VaultApplePayRequest class"""

        # Initialize members of the class
        if token is not APIHelper.SKIP:
            self.token = token 
        if card is not APIHelper.SKIP:
            self.card = card 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        token = dictionary.get("token") if dictionary.get("token") else APIHelper.SKIP
        card = ApplePayRequestCard.from_dictionary(dictionary.get('card')) if 'card' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(token,
                   card)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'token={(self.token if hasattr(self, "token") else None)!r}, '
                f'card={(self.card if hasattr(self, "card") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'token={(self.token if hasattr(self, "token") else None)!s}, '
                f'card={(self.card if hasattr(self, "card") else None)!s})')
