name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  flows-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
        pip install -r e2e-requirements.txt
    - name : Create env
      run: |
        echo "EMAIL=${{ secrets.EMAIL }}" >> .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Running E2E tests
      run: pytest --tracing=retain-on-failure
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/